Resources:
  TasksTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "Tasks"
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
        - AttributeName: "taskId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
        - AttributeName: "taskId"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"